/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNIPow */

#ifndef _Included_TestJNIPow
#define _Included_TestJNIPow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIPow
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_TestJNIPow_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     TestJNIPow
 * Method:    entry
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_TestJNIPow_entry
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
